Task_List_App2/config/routes.rb
TaskListApp2::Application.routes.draw do
  resources :tasks

  resources :task_lists

end

Task_List_App2/app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :task_list

	validates :title, :priority, :duedate, :Task_List_id, presence: { message: "must be present" }

  validates :priority, inclusion: { in: 1..10, message: 'needs to be between 1 and 10'  }
end

Task_List_App2/app/models/task_list.rb
class TaskList < ActiveRecord::Base
		has_many :tasks


	validates :name, :description, presence: { message: "must be present" }
  validates :name, uniqueness: true

end

Task_List_App2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :get_all_task_lists
  layout "todo_list"
  
  def get_all_task_lists
  	@all_task_lists = TaskList.all
  end
end

Task_List_App2/app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: [:show, :edit, :update, :destroy]

  # GET /task_lists
  # GET /task_lists.json
  def index
    @task_lists = TaskList.all
  end

  # GET /task_lists/1
  # GET /task_lists/1.json
  def show
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
  end

  # GET /task_lists/1/edit
  def edit
  end

  # POST /task_lists
  # POST /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)

    respond_to do |format|
      if @task_list.save
        format.html { redirect_to @task_list, notice: 'Task list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1
  # PATCH/PUT /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to @task_list, notice: 'Task list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1
  # DELETE /task_lists/1.json
  def destroy
    @task_list.destroy
    respond_to do |format|
      format.html { redirect_to task_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_list_params
      params.require(:task_list).permit(:name, :description)
    end
end

Task_List_App2/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :priority, :duedate, :iscomplete, :Task_List_id)
    end
end

Task_List_App2/app/helpers/application_helper.rb
module ApplicationHelper
end

Task_List_App2/app/helpers/task_lists_helper.rb
module TaskListsHelper
end

Task_List_App2/app/helpers/tasks_helper.rb
module TasksHelper
end

Task_List_App2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskListApp2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Task_List_App2/app/views/layouts/todo_list.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskListApp2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
To Do List
</header>
<div id="primary">
</div>
<div id="sidebar">
  <strong>Task Lists:</strong>
<ul>
  <% @all_task_lists.each do | task | %>
    <li><%= link_to task.name, task %> </li>
  <% end %>
</ul>
	
</div>
</body>
</html>

Task_List_App2/app/views/task_lists/_form.html.erb
<%= form_for(@task_list) do |f| %>
  <% if @task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
      <% @task_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Task_List_App2/app/views/task_lists/edit.html.erb
<h1>Editing task_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_list %> |
<%= link_to 'Back', task_lists_path %>

Task_List_App2/app/views/task_lists/index.html.erb
<h1>Listing task_lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @task_lists.each do |task_list| %>
      <tr>
        <td><%= task_list.name %></td>
        <td><%= task_list.description %></td>
        <td><%= link_to 'Show', task_list %></td>
        <td><%= link_to 'Edit', edit_task_list_path(task_list) %></td>
        <td><%= link_to 'Destroy', task_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task list', new_task_list_path %>

Task_List_App2/app/views/task_lists/new.html.erb
<h1>New task_list</h1>

<%= render 'form' %>

<%= link_to 'Back', task_lists_path %>

Task_List_App2/app/views/task_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task_list.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task_list.description %>
</p>

<p>
  <strong>Tasks:</strong>
<ul>
  <% @task_list.tasks.each do | task | %>
    <li><%= task.title %> </li>
  <% end %>
</ul>
</p>

<%= link_to 'Edit', edit_task_list_path(@task_list) %> |
<%= link_to 'Back', task_lists_path %>

Task_List_App2/app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :duedate %><br>
    <%= f.date_select :duedate %>
  </div>
  <div class="field">
    <%= f.label :iscomplete %><br>
    <%= f.check_box :iscomplete %>
  </div>
  <div class="field">
    <%= f.label :Task_List_id %><br>
    <%= f.collection_select :Task_List_id, TaskList.all, :id, :name, prompt: 'Please select a list...' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Task_List_App2/app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

Task_List_App2/app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Priority</th>
      <th>Duedate</th>
      <th>Iscomplete</th>
      <th>Task list</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.priority %></td>
        <td><%= task.duedate %></td>
        <td><%= task.iscomplete %></td>
        <!-- jarp: should be showing the task's name -->
        <td><%= task.Task_List_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

Task_List_App2/app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

Task_List_App2/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Duedate:</strong>
  <%= @task.duedate %>
</p>

<p>
  <strong>Iscomplete:</strong>
  <%= @task.iscomplete %>
</p>

<p>
  <strong>Task list:</strong>
  <%= @task.Task_List_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>